=== BelkhousNabil/Projet-r-alis-s/Projet de WEB/Application de gestion des STB/ProjectWeb2/server/src/main/resources/STB.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://univ.fr/stb" xmlns="http://univ.fr/stb">
	
	<xs:element name="stb">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Titre" type="xs:string"/>
				<xs:element name="Version" type="xs:string"/>
				<xs:element name="Date" type="xs:date"/>
				<xs:element name="Description" type="xs:string"/>
				<xs:element name="Client" minOccurs="1">
					<xs:complexType>        
						<xs:sequence>       
							<xs:element name="Entite" type="xs:string"/>
							<xs:element name="Contact" type="xs:string"/>
							<xs:element name="CP" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Equipe" minOccurs="2" maxOccurs="7">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nom" type="xs:string"/>
							<xs:element name="prenom" type="xs:string"/>
							<xs:element name="gender" type="xs:boolean"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="Fonctionnalite" minOccurs="2" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Description" type="xs:string"/>
							
							<xs:element name="Priorite">
							  <xs:simpleType>
								<xs:restriction base="xs:integer">
								  <xs:minInclusive value="0"/>
								  <xs:maxInclusive value="10"/>
								</xs:restriction>
							  </xs:simpleType>
							</xs:element>
							
							<xs:element name="Exigence" minOccurs="2" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Identifiant" type="xs:string"/>
										<xs:element name="Description" type="xs:string"/>
										<xs:element name="Priorite">
										  <xs:simpleType>
											<xs:restriction base="xs:integer">
											  <xs:minInclusive value="0"/>
											  <xs:maxInclusive value="10"/>
											</xs:restriction>
										  </xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Commentaire" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			
		</xs:complexType>
		
	</xs:element>
	
</xs:schema>

=== BelkhousNabil/Projet-r-alis-s/Projet de WEB/Application de gestion des STB/ProjectWeb2/STB_TEST.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:stb xmlns:p="http://univ.fr/stb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/stb STB.xsd ">
  <Titre>Projet Web 2</Titre>
  <Version>1.0</Version>
  <Date>2016-04-26</Date>
  <Description>STB pour le projet de web</Description>
  <Client>
    <Entite>Université de Rouen</Entite>
    <Contact>CLient: S.HERAUVILLE</Contact>
    <CP>76000</CP>
  </Client>
  <Equipe>
    <nom>BELKHOUS</nom>
    <prenom>Nabil</prenom>
    <gender>true</gender>
  </Equipe>
  <Equipe>
    <nom>Zebouchi</nom>
    <prenom>Mohammed</prenom>
    <gender>true</gender>
  </Equipe>

  <Fonctionnalite>
    <Description>Ajout de STB</Description>
    <Priorite>10</Priorite>
    <Exigence>
      <Identifiant>Client</Identifiant>
      <Description>Ajouter à partir d'un formulaire</Description>
      <Priorite>10</Priorite>
    </Exigence>
	<Exigence>
      <Identifiant>Client</Identifiant>
      <Description>Ajouter un fichier</Description>
      <Priorite>10</Priorite>
    </Exigence>
    <Exigence>
      <Identifiant>But du projet</Identifiant>
      <Description>Le resultat final</Description>
      <Priorite>1</Priorite>
    </Exigence>
  </Fonctionnalite>
  
  <Fonctionnalite>
    <Description>Résumé</Description>
    <Priorite>10</Priorite>
    <Exigence>
      <Identifiant>Client</Identifiant>
      <Description>Afficher résumé STB</Description>
      <Priorite>10</Priorite>
    </Exigence>
	<Exigence>
      <Identifiant>Client</Identifiant>
      <Description>Afficher résumé des STBs</Description>
      <Priorite>10</Priorite>
    </Exigence>
    <Exigence>
      <Identifiant>Creation à partir de l'IHM des diagrammes</Identifiant>
      <Description>Diagrammes UML</Description>
      <Priorite>2</Priorite>
    </Exigence>
  </Fonctionnalite>
  
  <Fonctionnalite>
    <Description>Accueil</Description>
    <Priorite>10</Priorite>
    <Exigence>
      <Identifiant>Membres</Identifiant>
      <Description>Afficher Membres projet</Description>
      <Priorite>10</Priorite>
    </Exigence>
	<Exigence>
      <Identifiant>Nombre STBs</Identifiant>
      <Description>Afficher le nombre de STBs</Description>
      <Priorite>10</Priorite>
    </Exigence>
    <Exigence>
      <Identifiant>à partir d'un fichier Java générer le diagramme de Classe</Identifiant>
      <Description>Obtention d'un diagramme</Description>
	  <Priorite>5</Priorite>
    </Exigence>
  </Fonctionnalite>
  <Commentaire> Projet réalisé par Belkhous et Zebouchi</Commentaire> 
  
</p:stb>
